name: Build, Version, and Publish

on:
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pawapay_node

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Format Code
        run: yarn format

  publish:
    needs: [ 'checkout' ]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pawapay_node

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn install

      - name: Format Code
        run: yarn format

      - name: Build the package
        run: yarn build

      - name: Verify dist folder
        run: ls -la dist

      - name: Bump version & push
        run: |
          git config --global user.name 'JoelFickson CI USER'
          git config --global user.email 'joelfickson@users.noreply.github.com'

          npm version patch -m "Bump version to %s [skip ci]"
          git push && git push --tags


      - name: Commit changes
        run: |
          git config --global user.name 'CI User'
          git config --global user.email 'CI@users.noreply.github.com'
          git add .
          git commit -m "Bump package version [skip ci]"
          git push

      - name: Push to NPM Registry
        run: npm publish --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

